#!/usr/bin/expect

set prompt "\u001b\[0;37m$\u001b\[00m "

set host_ip [lindex $argv 0]
set subnet_id [lindex $argv 1]
set wallet_key [lindex $argv 2]
set admin_key [lindex $argv 3]

spawn ssh -o StrictHostKeyChecking=no $host_ip
expect $prompt

# disable timeout so we can wait for the commands to finish
set timeout -1

send "sudo lit os guest template create node\n"
expect $prompt

send "sudo lit os guest template ls\n"

expect $prompt

# right here you would run the below command, substituting the subnet id and template id.  
# the template id comes from the output of the previous command but we don't have the
# code in place to parse the latest yet

# sudo lit os guest template release cf706619 \
#   --subnet-id 404f4ce3f2547a380774a293ab44c471016ac9cf

send "exit\r"
expect eof
